'''

389. Find the Difference

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
'''
s = "abcd"
t = "abcde"
Output =  "e"


def findTheDifference(s ,t):
    lst1 = []
    for i in s:
        lst1.append(i)
    # print(lst1)
    
    lst2 = []
    for k in t:
        lst2.append(k)
    # print(lst2)

    # print(lst1-lst2)

    return (set(lst1).intersection(set(lst2)))

print(findTheDifference(s ,t))